import os
import librosa
import config
import soundfile as sf
import numpy as np

from modules.analysis import analyze_audio_features, enforce_bpm
from modules.smoothing import apply_legato_overlap, enforce_pitch_limit
from modules.dynamic import apply_dynamic_compression, apply_lfo_modulation
from modules.spectral import apply_low_pass_filter, apply_high_pass_filter, apply_parametric_eq, normalize_amplitude
# from modules.drums import reduce_transient_attack



def mix_stems(stems: list, weights: list = None):
    """
    Sum multiple audio stems into a single mixed track.
    Optionally apply per-stem volume weights before summing.

    Each stem must have the same shape. If shapes differ slightly due to
    DSP processing (e.g. legato tail extension), stems are padded to the
    longest length before mixing.

    Args:
        stems   : list of np.ndarray — list of audio arrays to mix together
        weights : list of float      — optional volume multiplier per stem
                                       Ex: [1.0, 0.8, 0.6] = melody full, bass 80%, drums 60%
                                       If None, all stems are mixed at equal volume (1.0)

    Returns:
        np.ndarray — mixed audio, shape matches the longest input stem
    """
    # Default to equal weights if not specified
    if weights is None:
        weights = [1.0] * len(stems)

    # Find the longest stem length so shorter stems can be zero-padded to match
    max_length = max(s.shape[-1] for s in stems)

    mixed = None
    for stem, weight in zip(stems, weights):
        # Pad stem to max_length along the sample axis (axis=-1 works for mono and stereo)
        padded = librosa.util.fix_length(stem, size=max_length, axis=-1)

        # Apply volume weight and accumulate into the mix
        if mixed is None:
            mixed = padded * weight
        else:
            mixed = mixed + padded * weight

    return mixed


def process_therapeutic_track(song_folder, original_folder, output_folder, sample_rate=config.SAMPLE_RATE):
    """
    Full end-to-end ASD therapy processing pipeline for a single song.
    Loads Demucs-separated stems, applies all DSP modules, mixes and
    exports the final therapeutic track.

    Expected input folder structure (output of Demucs):
        song_folder/
            melody.wav  ← melody / main instrument
            bass.wav    ← bass line
            drums.wav   ← drum track

    Args:
        song_folder  : str — path to folder containing Demucs stem files
        output_folder: str — path where the processed output will be saved
        sample_rate  : int — sample rate of all audio files (default 48000)

    Returns:
        str — full path to the saved output file
    """
    os.makedirs(output_folder, exist_ok=True)

    # ── 1. Load Isolated Stems (Generated by Demucs) ──
    # librosa.load returns (audio_array, sample_rate)
    # mono=False preserves stereo channels as shape (2, samples)
    print("[1/6] Loading stems...")
    melody_raw, _ = librosa.load(os.path.join(song_folder, "melody.wav"), sr=sample_rate, mono=False)
    bass_raw,   _ = librosa.load(os.path.join(song_folder, "bass.wav"),   sr=sample_rate, mono=False)
    # drum_raw,   _ = librosa.load(os.path.join(song_folder, "drums.wav"),  sr=sample_rate, mono=False)

    song_name = os.path.basename(os.path.normpath(song_folder))
    original_raw, _ = librosa.load(os.path.join(original_folder, f"{song_name}.wav"), sr = sample_rate, mono = False)

    # ── 2. Compliance Check & Base Correction ──
    # Detect BPM from drums — most rhythmically stable stem, highest onset clarity
    # Detect pitch from melody — drums have no pitch to analyze
    print("[2/6] Analyzing features and syncing BPM...")

    features = analyze_audio_features(melody_raw, original_raw, sample_rate)
    current_bpm   = features["bpm"]
    is_bpm_valid  = features["is_bpm_valid"]
    max_pitch_jump = features["max_pitch_jump"]

    if not is_bpm_valid:
        # BPM outside 60-80 → stretch all stems to 60 BPM using drum-detected BPM as source of truth
        melody_synced = enforce_bpm(melody_raw, current_bpm, target_bpm = 60)
        bass_synced   = enforce_bpm(bass_raw,   current_bpm, target_bpm = 60)
        # drum_synced   = enforce_bpm(drum_raw,   current_bpm, target_bpm = 60)
        print(f"      Detected BPM: {current_bpm:.1f} | enforcing to 60 BPM")
    else:
        # BPM already valid → use raw stems directly, no stretching needed
        melody_synced = melody_raw
        bass_synced   = bass_raw
        # drum_synced   = drum_raw
        print(f"      Detected BPM: {current_bpm:.1f} | BPM valid → skipping")

    print(f"      Max pitch jump: {max_pitch_jump:.1f} semitones")

    # ── 3. Process Melody ──
    # Apply full therapy DSP chain: smooth notes, limit pitch jumps,
    # cut harsh highs, compress dynamics, add breathing LFO
    print("[3/6] Processing melody stem...")
    
    # Legato requires mono input — take left channel if stereo
    if melody_synced.ndim > 1:
        melody_mono = np.mean(melody_synced, axis=0)
    else:
        melody_mono = melody_synced

    # Cut off trash sound such as bass, drum and vocal which have not been cleaned correctly
    melody_dsp = apply_high_pass_filter(melody_mono, sample_rate=sample_rate, cutoff_freq=100)

    melody_dsp  = apply_legato_overlap(
        melody_mono, 
        sr=sample_rate,
        target_overlap_percentage = 0.65 # Reduce from 75% to 65% so it decay faster -> in range 70-80% legato overlap   
    )

    # Use max_pitch_jump as a gate — skip expensive enforce_pitch_limit
    # if melody already meets the 12 semitone limit (librosa.pyin is slow)
    if max_pitch_jump > 12:
        print(f"      Pitch jump {max_pitch_jump:.1f} semitones exceeds limit → enforcing...")
        melody_dsp = enforce_pitch_limit(melody_dsp, sample_rate, stem_type="melody")
    else:
        print(f"      Pitch jump {max_pitch_jump:.1f} semitones within limit → skipping")

    melody_dsp = apply_low_pass_filter(melody_dsp, cutoff_freq=5000, sample_rate=sample_rate)

    melody_dsp = apply_dynamic_compression(
        melody_dsp,
        sample_rate=sample_rate,
        attack_ms=5.0,        # ← từ 10ms xuống 5ms: react nhanh hơn
        release_ms=150.0      # ← từ 100ms lên 150ms: recover chậm hơn = smoother
    )

    # ── 4. Process Bass ──
    # Boost warm low-mid frequencies, compress and apply LFO breathing
    print("[4/6] Processing bass stem...")
    bass_dsp = apply_high_pass_filter(bass_synced, sample_rate = sample_rate, cutoff_freq = 80)
    bass_dsp = apply_parametric_eq(bass_dsp, sample_rate=sample_rate, center_freq=250)

    bass_dsp = apply_dynamic_compression(
        bass_dsp,
        sample_rate=sample_rate,
        attack_ms=5.0,
        release_ms=150.0
    )

    # # ── 5. Process Drums ──
    # # Keep only the sub-thump (cut above 80Hz) and soften all sharp transient hits
    # # cutoff_freq=80Hz: removes the crack/snap of the drum, keeps only the deep body thump
    # print("[5/7] Processing drum stem...")
    # drum_dsp = apply_low_pass_filter(drum_synced, cutoff_freq=5000, sample_rate=sample_rate)
    # drum_dsp = apply_high_pass_filter(drum_dsp, sample_rate = sample_rate, cutoff_freq = 80)
    # drum_dsp = reduce_transient_attack(drum_dsp, sample_rate=sample_rate, attack_ms = 40, ratio = 8)

    # ── 6. Mixing & Normalization ──
    # Sum all 3 stems with volume weights:
    #   melody = 1.0 (full volume, leads the track)
    #   bass   = 0.8 (slightly quieter, supportive role)
    #   drums  = 0.5 (significantly quieter, just provides rhythmic pulse)
    # Then normalize the final mix to -1.0dB peak
    print("[5/6] Mixing and normalizing...")
    target_mix = mix_stems(
        stems=[melody_dsp, bass_dsp],
        weights=[1.0, 0.1]
    )

    # ── Thêm: Master bus compression trên toàn bộ mix ──
    # Compress lần cuối để đảm bảo dynamic range < 6dB trên output cuối
    target_mix = apply_dynamic_compression(
        target_mix,
        sample_rate=sample_rate,
        attack_ms=5.0,
        release_ms=200.0
    )

    # Apply lfo modulation after mixing all the files
    target_mix = apply_lfo_modulation(
        target_mix,
        sample_rate = sample_rate,
        rate_hz = 0.08,
        depth = 0.12
    )
    target_mix = normalize_amplitude(target_mix, peak_db=-1.0)

    # ── 7. Export ──
    # soundfile.write expects shape (samples,) for mono or (samples, channels) for stereo
    # numpy arrays from librosa are (channels, samples) → need to transpose for soundfile
    print("[6/6] Saving output...")
    song_name   = os.path.basename(os.path.normpath(song_folder))
    output_path = os.path.join(output_folder, f"{song_name}_therapeutic.wav")

    # Transpose stereo from (channels, samples) → (samples, channels) for soundfile
    output_audio = target_mix.T if target_mix.ndim > 1 else target_mix
    sf.write(output_path, output_audio, sample_rate, subtype='PCM_24')

    print(f"      Saved → {output_path}")
    return output_path
